/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

/**
 *
 * @author SMK TELKOM
 */
public class Latihan4 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan4
     */
    public Latihan4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RPL = new javax.swing.JRadioButton();
        TKJ = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Code = new javax.swing.JCheckBox();
        Technic = new javax.swing.JCheckBox();
        Design = new javax.swing.JCheckBox();
        gaming = new javax.swing.JCheckBox();
        ok = new javax.swing.JButton();
        resetto = new javax.swing.JButton();
        quitto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tujuan = new javax.swing.JTextArea();
        Absen = new javax.swing.JTextField();
        Kelas = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Biodata Siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 18, 117, 18);

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        RPL.setBackground(new java.awt.Color(255, 204, 0));
        buttonGroup1.add(RPL);
        RPL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        RPL.setText("RPL");

        TKJ.setBackground(new java.awt.Color(255, 204, 0));
        buttonGroup1.add(TKJ);
        TKJ.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        TKJ.setText("TKJ");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Jurusan");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Hobi");

        Code.setBackground(new java.awt.Color(255, 204, 0));
        Code.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Code.setText("Programming");

        Technic.setBackground(new java.awt.Color(255, 204, 0));
        Technic.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Technic.setText("Teknisi");

        Design.setBackground(new java.awt.Color(255, 204, 0));
        Design.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Design.setText("Design");

        gaming.setBackground(new java.awt.Color(255, 204, 0));
        gaming.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        gaming.setText("Gaming");

        ok.setBackground(new java.awt.Color(255, 204, 0));
        ok.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        ok.setText("Submit");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        resetto.setBackground(new java.awt.Color(255, 204, 0));
        resetto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        resetto.setText("Reset");
        resetto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resettoActionPerformed(evt);
            }
        });

        quitto.setBackground(new java.awt.Color(255, 204, 0));
        quitto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        quitto.setText("Exit");
        quitto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quittoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Hasil");

        tujuan.setColumns(20);
        tujuan.setRows(5);
        jScrollPane2.setViewportView(tujuan);

        Absen.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        Kelas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        Nama.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Absen");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Kelas");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Nama");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(44, 44, 44)
                        .addComponent(Code)
                        .addGap(18, 18, 18)
                        .addComponent(Technic))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(gaming)
                        .addGap(52, 52, 52)
                        .addComponent(Design))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ok)
                        .addGap(18, 18, 18)
                        .addComponent(resetto)
                        .addGap(18, 18, 18)
                        .addComponent(quitto))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addComponent(RPL)
                        .addGap(18, 18, 18)
                        .addComponent(TKJ))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Absen, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(Kelas)
                            .addComponent(Nama))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Absen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RPL)
                        .addComponent(jLabel5))
                    .addComponent(TKJ))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(Code)
                    .addComponent(Technic))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gaming)
                    .addComponent(Design))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ok)
                    .addComponent(resetto)
                    .addComponent(quitto))
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 532, 461);

        setSize(new java.awt.Dimension(545, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        
        String nama =Nama.getText();
        String kelas = Kelas.getText();
        String absen = Absen.getText();
        String jurusan;
        String hobi = "";
        
        if (RPL.isSelected())
            jurusan = "RPL";
        else if (TKJ.isSelected())
            jurusan = "TKJ";
        else jurusan = "";
        
        
        if(Code.isSelected())
            hobi += Code.getText()+ ", ";
        if(gaming.isSelected())
            hobi += gaming.getText()+ ", ";
        if(Technic.isSelected())
            hobi += Technic.getText()+ ", ";
        if(Design.isSelected())
            hobi += Design.getText()+ ", ";
        tujuan.setText("Nama Siswa : " +nama+ "\n Absen : " +absen+"\n Jurusan : "+jurusan+"\n Hobi : "+hobi);
    }//GEN-LAST:event_okActionPerformed

    private void resettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resettoActionPerformed
        tujuan.setText("");
        Nama.setText("");
        Kelas.setText("");
        Absen.setText("");
        buttonGroup1.clearSelection();
        Code.setSelected(false);
        gaming.setSelected(false);
        Technic.setSelected(false);
        Design.setSelected(false);
    }//GEN-LAST:event_resettoActionPerformed

    private void quittoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quittoActionPerformed
        dispose();
    }//GEN-LAST:event_quittoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JCheckBox Code;
    private javax.swing.JCheckBox Design;
    private javax.swing.JTextField Kelas;
    private javax.swing.JTextField Nama;
    private javax.swing.JRadioButton RPL;
    private javax.swing.JRadioButton TKJ;
    private javax.swing.JCheckBox Technic;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox gaming;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton ok;
    private javax.swing.JButton quitto;
    private javax.swing.JButton resetto;
    private javax.swing.JTextArea tujuan;
    // End of variables declaration//GEN-END:variables
}
